### ISSUE TITLE
The corruption datasets

### ISSUE THREAD

**Issue by syh-hue** [MinghuiChen43/CIL-ReID#2]
Hello, will the corruption dataset be automatically generated and saved after the code is run? Such as Market-1501-C, MSMT17-C, CUHK03-C, etc.

**Comment by MinghuiChen43** [comment]
> 

In evaluation, corrupted images will be generated on the fly but not be saved locally. More details can be found in the code (see ./datasets/make_dataloader.py).

**Comment by syh-hue** [comment]
> > 
> 
> 在评估中，损坏的图像将即时生成，但不会保存在本地。更多细节可以在代码中找到（参见 ./datasets/make_dataloader.py）。

在我训练之后，测试test中出现这个问题，始终没能解决
Traceback (most recent call last):
  File "F:/workspace/CIL-ReID-main/test.py", line 72, in <module>
    mINP, mAP, rank1, rank5, rank10 = do_inference(
  File "F:\workspace\CIL-ReID-main\processor\processor.py", line 208, in do_inference
    logger.info("mAP: {:.2%}".format(mAP))
TypeError: unsupported format string passed to list.__format__
请问这个该如何解决？

**Comment by LY-cmd-xtt** [comment]
> Hello, will the corruption dataset be automatically generated and saved after the code is run? Such as Market-1501-C, MSMT17-C, CUHK03-C, etc.

Excuse me, the structure of cuhk03 dataset does not have the three folders bounding_box_train, query and bounding_box_test, how should I run your code on this dataset?

**Comment by ChuxiaYang** [comment]
> > Hello, will the corruption dataset be automatically generated and saved after the code is run? Such as Market-1501-C, MSMT17-C, CUHK03-C, etc.
> 
> Excuse me, the structure of cuhk03 dataset does not have the three folders bounding_box_train, query and bounding_box_test, how should I run your code on this dataset?

可以看看这个链接https://blog.csdn.net/qq_39220334/article/details/121448343

**Comment by LY-cmd-xtt** [comment]
> > > Hello, will the corruption dataset be automatically generated and saved after the code is run? Such as Market-1501-C, MSMT17-C, CUHK03-C, etc.
> > 
> > 
> > Excuse me, the structure of cuhk03 dataset does not have the three folders bounding_box_train, query and bounding_box_test, how should I run your code on this dataset?
> 
> 可以看看这个链接https://blog.csdn.net/qq_39220334/article/details/121448343

thank you very much！
