### ISSUE TITLE
Why did I get so much higher numbers than you did in your paper?

### ISSUE THREAD

**Issue by ChuxiaYang** [MinghuiChen43/CIL-ReID#5]
Thanks for your works. As you set up in your code, I used TransReID to reproduce on the dataset Market1501-C, but I got an incredible result without any modity. mINP=6.3, mAP=40.45, Rank-1=65.05 (Corrupted eval).   Is there something I'm not setting right？

**Comment by syh-hue** [comment]
I got almost the same result as you. Did you know what happened?

**Comment by ChuxiaYang** [comment]
It have a different code in metric.py
